### ISSUE TITLE
Wolfram.coffee error 

### ISSUE THREAD

**Issue by CODEPLATO** [github/hubot-scripts#1521]
I recently ran this wolfram.coffee script and got this error, could anyone help me resolve the issue. Thanks

Error: Cannot find module 'wolfram-alpha'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/angmingliang/myhubot/scripts/wolfram.coffee:1:11, <js>:4:13)
  at Object.<anonymous> (/Users/angmingliang/myhubot/scripts/wolfram.coffee:1:1, <js>:24:4)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/angmingliang/myhubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (/Users/angmingliang/myhubot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Robot.loadFile (/Users/angmingliang/myHubot/node_modules/hubot/src/robot.coffee:218:9, <js>:164:11)
  at /Users/angmingliang/myHubot/node_modules/hubot/src/robot.coffee:234:11, <js>:184:33
  at Object.cb [as oncomplete] (fs.js:168:19)

**Comment by technicalpickles** [comment]
This repository has been deprecated for awhile in favor of npm packages. As @notpeter said, it's been https://github.com/notpeter/hubot-wolfram so I'd give that a try to see if it works any better. We are in the process of finding scripts that have been extracted, and deprecating them over in #1641
